Fix: Validate required Telegram secrets

diff --git a/.github/workflows/post_to_tg_channel.yml b/.github/workflows/post_to_tg_channel.yml
--- a/.github/workflows/post_to_tg_channel.yml
+++ b/.github/workflows/post_to_tg_channel.yml
@@ -49,12 +49,15 @@ jobs:
         mkdir -p updates posted
 
     - name: Validate required Telegram secrets
+      run: |
+        # Check if required secrets are set
+        [ -z "$TELEGRAM_BOT_TOKEN" ] && echo "TELEGRAM_BOT_TOKEN is not set. Exiting." && exit 1
+        [ -z "$TELEGRAM_CHAT_ID" ] && echo "TELEGRAM_CHAT_ID is not set. Exiting." && exit 1
+
+        echo "All required Telegram secrets are set."
       env:
         TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
         TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
-      run: |
-        [ -z "$TELEGRAM_BOT_TOKEN" ] && echo "TELEGRAM_BOT_TOKEN is not set." && exit 1
-        [ -z "$TELEGRAM_CHAT_ID" ] && echo "TELEGRAM_CHAT_ID is not set." && exit 1
 
     - name: Post news files to Telegram
       env:
